from .fixed_stddev_policy import FixedStdActorCriticPolicy
from stable_baselines3.common.policies import register_policy

CustomMlpPolicy = FixedStdActorCriticPolicy

register_policy("FixedStddevMlpPolicy", FixedStdActorCriticPolicy)